### ISSUE TITLE
Добавить кэширование расписания

### ISSUE THREAD

**Issue by dyakovri** [profcomff/timetable-webapp#29]
Кэшировать расписание на неделю-две вперед и хранить в LocalStorage/[IndexedDB](https://learn.javascript.ru/indexeddb)

**Comment by Annndruha** [comment]
Кэш не работает! Как воспроизвести:

1) Открыл приложение, выбрал группу, сохранил, вижу пары на один день
2) Закрыл приложение, отключил интернет
3) Открыл приложение, переключаюсь на другой день, висит вечная загрузка

![Image](https://user-images.githubusercontent.com/51162917/188281434-8b269810-4189-4f86-991e-0cf9e24656d5.png)
