### ISSUE TITLE
Есть возможность сохранить группу "Не выбрано"

### ISSUE THREAD

**Issue by dyakovri** [profcomff/timetable-webapp#33]
Если просто сохранить "Не выбрано", то вылазит окно с предупреждением, всё ок.
Но если выбрать группу, а затем поменять на "Не выбрано", то сохранение работает и открывается белое окно.

**Comment by Annndruha** [comment]
`src/views/Init.vue saveGroup` в if пропускает значение null внутрь условия и в timetable-group-id сохраняется null

**Comment by ilya101master** [comment]
js почему-то считает, что null это строка, по умолчанию назначен индекс -1

**Comment by Annndruha** [comment]
Issue была закрыта. Она закрыта как починенное в тесте?  На проде всё ещё можно сохранить так "Не выбрано"

**Comment by ilya101master** [comment]
Коммит с фиксом ожидает своего пр
