### ISSUE TITLE
Плохо отображаются длинные названия пар

### ISSUE THREAD

**Issue by dyakovri** [profcomff/timetable-webapp#35]
Нужно уменьшить отступы при переносе текста и сделать блок пар адаптируемый под контент в нём.

![Image](https://user-images.githubusercontent.com/51162917/188281207-516f6223-fcee-4c57-a6c7-60b1af529733.png)

**Comment by ilya101master** [comment]
Трёхстрочные пары, я копал в рот это всё....

**Comment by ilya101master** [comment]
Добавлен scale для длинных названий пар
